### ISSUE TITLE
Offline image not load

### ISSUE THREAD

**Issue by roncallyt** [FrontendMasters/service-workers-offline#2]
Hi,

I am taking the Detecting Offline Status class, but when I set the Throttling value to offline the website tries to load the resource "images/offline.png" and can't, because it is simulating offline mode.

![Captura de tela 2021-06-26 125856](https://user-images.githubusercontent.com/6303124/123520381-672a9780-d67e-11eb-9d3d-6f84425ed34d.jpg)

![Captura de tela 2021-06-26 125853](https://user-images.githubusercontent.com/6303124/123520384-6f82d280-d67e-11eb-82c8-688b71035d06.jpg)

To solve this I prefetch the image with a link tag in the header of the HTML pages, is this correct? or is there another way to do this?

![Captura de tela 2021-06-26 130027](https://user-images.githubusercontent.com/6303124/123520392-7f9ab200-d67e-11eb-8a1e-d2a48e646e7a.jpg)

**Comment by DrPuneetGaur** [comment]
I am facing the same issue.

**Comment by MarcNq** [comment]
This happens because browsers are becoming smarter, and now they may not download an image if it's in an element with style `display: none` as an optimisation (a bad one if you contemplate offline flows).

A simple fix is to change the `style.css` file to have this instead of the original:
```
#connectivity-status.hidden {
    visibility: hidden;
}
```

This worked for me in Chrome 99. I hope they don't start avoiding prefetch also for `visibility: hidden` elements.
